# Setup
title:               Andrew Rivera
tagline:             'Software Developer'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://anrivera16.github.io/anrivera.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrew Rivera
  url:               https://twitter.com/mdo
  email:             23andrew16@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
